# Generated by Django 2.2.28 on 2023-03-07 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_ID', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_ID', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=30)),
                ('postcode', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('takeaway_option', models.CharField(default='yes', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_Rating', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('service_Rating', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('atmosphere_Rating', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('price_Rating', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('favourited', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=300)),
                ('cust_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Customer')),
                ('rest_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_ID', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('restaurant_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.Restaurant')),
                ('owner_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Owner')),
            ],
        ),
    ]
